<a href="https://colab.research.google.com/github/HimanshuMK/Neural-Network-from-Scratch/blob/main/practice_example_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

## Dense Layer

In [10]:
# Dense layer
class Layer_Dense :
  # Layer initialization
  def __init__ ( self , n_inputs , n_neurons ):
    # Initialize weights and biases
    self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros(( 1 , n_neurons))

  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases

  # Backward pass
  def backward ( self , dvalues ):
    # Gradients on parameters
    self.dweights = np.dot(self.inputs.T, dvalues)
    self.dbiases = np.sum(dvalues, axis = 0 , keepdims = True )
    # Gradient on values
    self.dinputs = np.dot(dvalues, self.weights.T)

In [11]:
# Mean Squared Error Loss and its gradient
def mse_loss(y_pred, y_true):
    return np.mean((y_pred - y_true) ** 2)

def mse_loss_gradient(y_pred, y_true):
    return 2 * (y_pred - y_true) / y_true.size

Creating a Neural Network for 3 input features and 1 sample and trying to fit it in the model with output as 1 neuron

In [12]:
np.random.seed(42)  # For reproducibility
layer = Layer_Dense(n_inputs=3, n_neurons=1)
print("Initial weights:", layer.weights)
print("Initial biases:", layer.biases)

inputs = np.array([[1.0, 2.0, 3.0]])
y_true = np.array([[1.0]])
learning_rate = 0.01

# Training loop
for i in range(20):  # Perform 5 iterations
    # Forward pass
    layer.forward(inputs)
    y_pred = layer.output

    # Compute the loss
    loss = mse_loss(y_pred, y_true)

    # Compute the gradient of the loss with respect to the output
    dvalues = mse_loss_gradient(y_pred, y_true)

    # Backward pass
    layer.backward(dvalues)

    # Update weights and biases
    layer.weights -= learning_rate * layer.dweights
    layer.biases -= learning_rate * layer.dbiases

    # Print the progress
    print(f"Iteration {i+1}:")
    print("Inputs:", layer.inputs)
    print("True output:", y_true)
    print("Predicted output:", y_pred)
    print("Loss:", loss)
    print("Updated weights:", layer.weights)
    print("Updated biases:", layer.biases)
    print()


Initial weights: [[ 0.04967142]
 [-0.01382643]
 [ 0.06476885]]
Initial biases: [[0.]]
Iteration 1:
Inputs: [[1. 2. 3.]]
True output: [[1.]]
Predicted output: [[0.21632512]]
Loss: 0.6141463230332932
Updated weights: [[0.06534491]
 [0.01752057]
 [0.11178935]]
Updated biases: [[0.0156735]]

Iteration 2:
Inputs: [[1. 2. 3.]]
True output: [[1.]]
Predicted output: [[0.45142758]]
Loss: 0.3009316982863137
Updated weights: [[0.07631636]
 [0.03946346]
 [0.14470369]]
Updated biases: [[0.02664495]]

Iteration 3:
Inputs: [[1. 2. 3.]]
True output: [[1.]]
Predicted output: [[0.61599931]]
Loss: 0.1474565321602936
Updated weights: [[0.08399638]
 [0.05482349]
 [0.16774373]]
Updated biases: [[0.03432496]]

Iteration 4:
Inputs: [[1. 2. 3.]]
True output: [[1.]]
Predicted output: [[0.73119951]]
Loss: 0.07225370075854394
Updated weights: [[0.08937238]
 [0.06557551]
 [0.18387176]]
Updated biases: [[0.03970097]]

Iteration 5:
Inputs: [[1. 2. 3.]]
True output: [[1.]]
Predicted output: [[0.81183966]]
Loss: 0.035

Since our Loss is getting reduced and predicted output is close to True output,
So our code is perfectly working.

Creating a Neural Network for 3 input features and 2 sample and trying to fit it in the model with output as 2 neuron

In [13]:
# now for 2 samples
np.random.seed(42)  # For reproducibility
layer = Layer_Dense(n_inputs=3, n_neurons=2)
print("Initial weights:\n", layer.weights)
print("Initial biases:\n", layer.biases)

inputs = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y_true = np.array([[1.0, 2.0], [3.0, 4.0]])
learning_rate = 0.01

# Training loop
for i in range(20):  # Perform 5 iterations
    # Forward pass
    layer.forward(inputs)
    y_pred = layer.output

    # Compute the loss
    loss = mse_loss(y_pred, y_true)

    # Compute the gradient of the loss with respect to the output
    dvalues = mse_loss_gradient(y_pred, y_true)

    # Backward pass
    layer.backward(dvalues)

    # Update weights and biases
    layer.weights -= learning_rate * layer.dweights
    layer.biases -= learning_rate * layer.dbiases

    # Print the progress
    print(f"Iteration {i+1}:")
    print("Inputs:", layer.inputs)
    print("True Outputs:", y_true)
    print("Predicted output:", y_pred)
    print("Loss:", loss)
    print("Updated weights:", layer.weights)
    print("Updated biases:", layer.biases)
    print()


Initial weights:
 [[ 0.04967142 -0.01382643]
 [ 0.06476885  0.15230299]
 [-0.02341534 -0.0234137 ]]
Initial biases:
 [[0. 0.]]
Iteration 1:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
True Outputs: [[1. 2.]
 [3. 4.]]
Predicted output: [[0.10896311 0.22053845]
 [0.38203791 0.56572703]]
Loss: 5.65209661712092
Updated weights: [[0.10648584 0.06375634]
 [0.13912828 0.25595443]
 [0.06848908 0.10630642]]
Updated biases: [[0.01754499 0.02606867]]

Iteration 2:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
True Outputs: [[1. 2.]
 [3. 4.]]
Predicted output: [[0.60775462 0.92065311]
 [1.55006421 2.19870465]]
Loss: 1.6664562244365677
Updated weights: [[0.13744578 0.10517898]
 [0.17929912 0.31178028]
 [0.11787083 0.17653548]]
Updated biases: [[0.0267559  0.04047188]]

Iteration 3:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
True Outputs: [[1. 2.]
 [3. 4.]]
Predicted output: [[0.87641243 1.29881786]
 [2.18025965 3.07930207]]
Loss: 0.5066472978576841
Updated weights: [[0.15445853 0.12709885]
 [0.20102851 0.34180955]
 [0.14431686 0.21

Since our Loss is getting reduced and predicted output is close to True output,
So our code is perfectly working.

Now for Dense Layer with ReLU activation

In [14]:
import numpy as np

In [15]:
# Dense layer
class Layer_Dense :
  # Layer initialization
  def __init__ ( self , n_inputs , n_neurons ):
    # Initialize weights and biases
    self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros(( 1 , n_neurons))

  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases

  # Backward pass
  def backward ( self , dvalues ):
    # Gradients on parameters
    self.dweights = np.dot(self.inputs.T, dvalues)
    self.dbiases = np.sum(dvalues, axis = 0 , keepdims = True )
    # Gradient on values
    self.dinputs = np.dot(dvalues, self.weights.T)

In [16]:
# ReLU activation
class Activation_ReLU :
  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs
    self.output = np.maximum( 0 , inputs)

  # Backward pass
  def backward ( self , dvalues ):
    # Since we need to modify original variable,
    # let's make a copy of values first
    self.dinputs = dvalues.copy()
    # Zero gradient where input values were negative
    self.dinputs[self.inputs <= 0 ] = 0

Creating a Dense Layer with ReLU activation for 3 input features and 2 sample and trying to fit it in the model with output as 2 neuron

In [17]:
# now including relu activation

np.random.seed(42)  # For reproducibility

# Initialize layers
layer = Layer_Dense(n_inputs=3, n_neurons=2)
activation1 = Activation_ReLU()

print("Initial weights:\n", layer.weights)
print("Initial biases:\n", layer.biases)


inputs = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y_true = np.array([[1.0, 2.0], [3.0, 4.0]])
learning_rate = 0.01


# Training loop
for i in range(20):  # Perform 20 iterations
    # Forward pass
    layer.forward(inputs)
    layer_out = layer.output

    activation1.forward(layer.output)
    y_pred = activation1.output

    # Compute the loss
    loss = mse_loss(y_pred, y_true)

    # Compute the gradient of the loss with respect to the output
    dvalues = mse_loss_gradient(y_pred, y_true)

    # Backward pass

    activation1.backward(dvalues)
    layer.backward(activation1.dinputs)

    # Update weights and biases
    layer.weights -= learning_rate * layer.dweights
    layer.biases -= learning_rate * layer.dbiases

    # Print the progress
    print(f"Iteration {i+1}:")
    print("Inputs:", layer.inputs)
    print("layer_out:", layer_out)
    print("True Outputs:", y_true)
    print("Activation/Predicted output:", y_pred)
    print("Loss:", loss)
    print("Updated weights:", layer.weights)
    print("Updated biases:", layer.biases)
    print()


Initial weights:
 [[ 0.04967142 -0.01382643]
 [ 0.06476885  0.15230299]
 [-0.02341534 -0.0234137 ]]
Initial biases:
 [[0. 0.]]
Iteration 1:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
layer_out: [[0.10896311 0.22053845]
 [0.38203791 0.56572703]]
True Outputs: [[1. 2.]
 [3. 4.]]
Activation/Predicted output: [[0.10896311 0.22053845]
 [0.38203791 0.56572703]]
Loss: 5.65209661712092
Updated weights: [[0.10648584 0.06375634]
 [0.13912828 0.25595443]
 [0.06848908 0.10630642]]
Updated biases: [[0.01754499 0.02606867]]

Iteration 2:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
layer_out: [[0.60775462 0.92065311]
 [1.55006421 2.19870465]]
True Outputs: [[1. 2.]
 [3. 4.]]
Activation/Predicted output: [[0.60775462 0.92065311]
 [1.55006421 2.19870465]]
Loss: 1.6664562244365677
Updated weights: [[0.13744578 0.10517898]
 [0.17929912 0.31178028]
 [0.11787083 0.17653548]]
Updated biases: [[0.0267559  0.04047188]]

Iteration 3:
Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
layer_out: [[0.87641243 1.29881786]
 [2.18025965 3.07930207]]
Tru

Since our Loss is getting reduced and predicted output is close to True output,
So our code is perfectly working.

Now for Dense Layer with SoftMax activation.

In [18]:
# now for Softmax Activation
import numpy as np

# Dense layer
class Layer_Dense :
  # Layer initialization
  def __init__ ( self , n_inputs , n_neurons ):
    # Initialize weights and biases
    self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros(( 1 , n_neurons))

  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases

  # Backward pass
  def backward ( self , dvalues ):
    # Gradients on parameters
    self.dweights = np.dot(self.inputs.T, dvalues)
    self.dbiases = np.sum(dvalues, axis = 0 , keepdims = True )
    # Gradient on values
    self.dinputs = np.dot(dvalues, self.weights.T)


class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Remember input values
        self.inputs = inputs
        # Subtract max value for numerical stability
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        # Normalize probabilities
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

    # Backward pass
    def backward(self, dvalues):
        # Create uninitialized array
        self.dinputs = np.empty_like(dvalues)
        # Enumerate outputs and gradients
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):
            # Flatten output array
            single_output = single_output.reshape(-1, 1)
            # Calculate Jacobian matrix of the output and its gradient
            jacobian_matrix = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            # Calculate sample-wise gradient
            self.dinputs[index] = np.dot(jacobian_matrix, single_dvalues)



In [19]:
# Categorical Cross-Entropy Loss
def categorical_crossentropy_loss(y_pred, y_true):
    # Clip data to prevent division by 0
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    # Calculate loss
    correct_confidences = y_pred[range(len(y_pred)), y_true]
    return -np.mean(np.log(correct_confidences))


# Gradient of Categorical Cross-Entropy Loss
def categorical_crossentropy_loss_gradient(y_pred, y_true):
    samples = len(y_pred)
    labels = len(y_pred[0])

    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)

    # Initialize the gradient
    gradients = np.zeros_like(y_pred)

    # Convert labels to one-hot if they are not
    if len(y_true.shape) == 1:
        y_true = np.eye(labels)[y_true]

    # Calculate gradient
    gradients = -y_true / y_pred
    gradients = gradients / samples

    return gradients


Creating a Dense Layer with SoftMax activation for 3 input features and 2 sample and trying to fit it in the model with output as 2 neuron

In [20]:
np.random.seed(42)  # For reproducibility

# Initialize layers
dense1 = Layer_Dense(n_inputs=3, n_neurons=2)
activation1 = Activation_Softmax()

print("Initial weights:\n", dense1.weights)
print("Initial biases:\n", dense1.biases)

inputs = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y_true = np.array([0, 1])
learning_rate = 0.1


# Training loop
for i in range(10):  # Perform 5 iterations

    # Forward pass through dense layer
    dense1.forward(inputs)

    # Forward pass through softmax activation layer
    activation1.forward(dense1.output)

    y_pred = activation1.output

    # Compute the loss
    loss = categorical_crossentropy_loss(activation1.output, y_true)

    # Compute the gradient of the loss with respect to the output
    dvalues = categorical_crossentropy_loss_gradient(activation1.output, y_true)

    # Backward pass
    activation1.backward(dvalues)
    dense1.backward(activation1.dinputs)

    # Update weights and biases
    dense1.weights -= learning_rate * dense1.dweights
    dense1.biases -= learning_rate * dense1.dbiases

    # Print the progress
    print(f"Iteration {i+1}:")
    print("Dense layer Inputs:", dense1.inputs)
    print("Dense layer output:", dense1.output)
    print("True Outputs:", y_true)
    print("Softmax Activation/Predicted output:", y_pred)
    print("Loss:", loss)
    print("Updated weights:", dense1.weights)
    print("Updated biases:", dense1.biases)
    print()


Initial weights:
 [[ 0.04967142 -0.01382643]
 [ 0.06476885  0.15230299]
 [-0.02341534 -0.0234137 ]]
Initial biases:
 [[0. 0.]]
Iteration 1:
Dense layer Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
Dense layer output: [[0.10896311 0.22053845]
 [0.38203791 0.56572703]]
True Outputs: [0 1]
Softmax Activation/Predicted output: [[0.47213507 0.52786493]
 [0.45420641 0.54579359]]
Loss: 0.6780022950324187
Updated weights: [[-0.01477662  0.0506216 ]
 [ 0.00400375  0.21306809]
 [-0.08049752  0.03366849]]
Updated biases: [[ 0.00368293 -0.00368293]]

Iteration 2:
Dense layer Inputs: [[1. 2. 3.]
 [4. 5. 6.]]
Dense layer output: [[-0.24457876  0.57408033]
 [-0.51838995  1.46615488]]
True Outputs: [0 1]
Softmax Activation/Predicted output: [[0.30604837 0.69395163]
 [0.12083519 0.87916481]]
Loss: 0.6563975061565652
Updated weights: [[-0.00424608  0.04009106]
 [ 0.04319011  0.17388173]
 [-0.01265533 -0.0341737 ]]
Updated biases: [[ 0.03233875 -0.03233875]]

Iteration 3:
Dense layer Inputs: [[1. 2. 3.]
 [4. 5. 6.]]

Since our Loss is getting reduced and predicted output is close to True output,
So our code is perfectly working.

## Full Code upto this point

In [21]:
# Dense layer
class Layer_Dense :
  # Layer initialization
  def __init__ ( self , n_inputs , n_neurons ):
    # Initialize weights and biases
    self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros(( 1 , n_neurons))

  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases

  # Backward pass
  def backward ( self , dvalues ):
    # Gradients on parameters
    self.dweights = np.dot(self.inputs.T, dvalues)
    self.dbiases = np.sum(dvalues, axis = 0 , keepdims = True )
    # Gradient on values
    self.dinputs = np.dot(dvalues, self.weights.T)

################################################################################

# Mean Squared Error Loss and its gradient
def mse_loss(y_pred, y_true):
    return np.mean((y_pred - y_true) ** 2)

def mse_loss_gradient(y_pred, y_true):
    return 2 * (y_pred - y_true) / y_true.size

################################################################################

# ReLU activation
class Activation_ReLU :
  # Forward pass
  def forward ( self , inputs ):
    # Remember input values
    self.inputs = inputs
    # Calculate output values from inputs
    self.output = np.maximum( 0 , inputs)

  # Backward pass
  def backward ( self , dvalues ):
    # Since we need to modify original variable,
    # let's make a copy of values first
    self.dinputs = dvalues.copy()
    # Zero gradient where input values were negative
    self.dinputs[self.inputs <= 0 ] = 0

################################################################################

class Activation_Softmax:
    # Forward pass
    def forward(self, inputs):
        # Remember input values
        self.inputs = inputs
        # Subtract max value for numerical stability
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        # Normalize probabilities
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

    # Backward pass
    def backward(self, dvalues):
        # Create uninitialized array
        self.dinputs = np.empty_like(dvalues)
        # Enumerate outputs and gradients
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):
            # Flatten output array
            single_output = single_output.reshape(-1, 1)
            # Calculate Jacobian matrix of the output and its gradient
            jacobian_matrix = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            # Calculate sample-wise gradient
            self.dinputs[index] = np.dot(jacobian_matrix, single_dvalues)

################################################################################

# Categorical Cross-Entropy Loss
def categorical_crossentropy_loss(y_pred, y_true):
    # Clip data to prevent division by 0
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    # Calculate loss
    correct_confidences = y_pred[range(len(y_pred)), y_true]
    return -np.mean(np.log(correct_confidences))


# Gradient of Categorical Cross-Entropy Loss
def categorical_crossentropy_loss_gradient(y_pred, y_true):
    samples = len(y_pred)
    labels = len(y_pred[0])

    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)

    # Initialize the gradient
    gradients = np.zeros_like(y_pred)

    # Convert labels to one-hot if they are not
    if len(y_true.shape) == 1:
        y_true = np.eye(labels)[y_true]

    # Calculate gradient
    gradients = -y_true / y_pred
    gradients = gradients / samples

    return gradients


In [22]:
!pip install nnfs

In [23]:
import numpy as np
np.random.seed(0)
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import vertical_data
import matplotlib.pyplot as plt


Testing some test Code with optimizer

In [25]:
# Create dataset
X, y = spiral_data( samples = 100 , classes = 3 )

In [26]:
print(X.shape)
print(y.shape)

(300, 2)
(300,)


In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In normal optimizer loss is decreasing slowly and also accuracy is also increasing slowly

Common SGD vanilla Optimizer

In [29]:
## optimizers
#Common SGD Vanilla optimizer
class Optimizer_SGD :

  # Initialize optimizer - set settings,
  # learning rate of 1. is default for this optimizer
  def __init__ ( self , learning_rate = 1.0, decay = 0.):
    self.learning_rate = learning_rate
    self.current_learning_rate = learning_rate
    self.decay = decay
    self.iterations = 0

  # Call once before any parameter updates
  def pre_update_params ( self ):
    if self.decay:
      self.current_learning_rate = self.learning_rate *( 1. / ( 1. + self.decay * self.iterations))

  # Update parameters
  def update_params ( self , layer ):

    layer.weights += - self.current_learning_rate * layer.dweights
    layer.biases += - self.current_learning_rate * layer.dbiases

  # Call once after any parameter updates
  def post_update_params ( self ):
    self.iterations += 1



In [31]:
dense1 = Layer_Dense(2, 64)
activation1 = Activation_ReLU()
dense2 = Layer_Dense( 64 , 3 )
activation2 = Activation_Softmax()
# loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

# Create optimizer
optimizer = Optimizer_SGD(learning_rate = 1, decay = 1e-3)

# Train in loop
for epoch in range ( 10001 ):

    ##training
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    loss = categorical_crossentropy_loss(activation2.output, y)
    loss_grad = categorical_crossentropy_loss_gradient(activation2.output, y) #dvalues

    # loss = loss_activation.forward(dense2.output, y)

    predictions = np.argmax(activation2.output, axis = 1 )
    if len (y.shape) == 2 :
      y = np.argmax(y, axis = 1 )
    accuracy = np.mean(predictions == y)

    if not epoch % 100 :
      print(f"epoch:{epoch} ,acc:{accuracy:.3f} ,loss:{loss:.3f} ,lr:{optimizer.current_learning_rate}")


    # # Backward pass
    activation2.backward(loss_grad)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Print gradients
    # print (dense1.dweights)
    # print (dense1.dbiases)
    # print (dense2.dweights)
    # print (dense2.dbiases)

    # Update weights and biases
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch:0 ,acc:0.270 ,loss:1.102 ,lr:1
epoch:100 ,acc:0.403 ,loss:1.076 ,lr:0.9099181073703367
epoch:200 ,acc:0.410 ,loss:1.072 ,lr:0.8340283569641367
epoch:300 ,acc:0.423 ,loss:1.068 ,lr:0.7698229407236336
epoch:400 ,acc:0.420 ,loss:1.064 ,lr:0.7147962830593281
epoch:500 ,acc:0.413 ,loss:1.059 ,lr:0.66711140760507
epoch:600 ,acc:0.413 ,loss:1.053 ,lr:0.6253908692933083
epoch:700 ,acc:0.420 ,loss:1.046 ,lr:0.5885815185403178
epoch:800 ,acc:0.430 ,loss:1.040 ,lr:0.5558643690939411
epoch:900 ,acc:0.437 ,loss:1.032 ,lr:0.526592943654555
epoch:1000 ,acc:0.440 ,loss:1.023 ,lr:0.5002501250625312
epoch:1100 ,acc:0.463 ,loss:1.014 ,lr:0.4764173415912339
epoch:1200 ,acc:0.513 ,loss:1.003 ,lr:0.45475216007276037
epoch:1300 ,acc:0.537 ,loss:0.993 ,lr:0.43497172683775553
epoch:1400 ,acc:0.553 ,loss:0.983 ,lr:0.4168403501458941
epoch:1500 ,acc:0.573 ,loss:0.983 ,lr:0.4001600640256102
epoch:1600 ,acc:0.580 ,loss:0.982 ,lr:0.3847633705271258
epoch:1700 ,acc:0.597 ,loss:0.975 ,lr:0.3705075954057058
epoc

In normal Vanilla optimizer loss is decreasing slowly and also accuracy is also increasing slowly

SGD optimizer with Momentum and Vanilla

In [34]:
# SGD optimizer with momentum and vanilla
class Optimizer_SGD:

    # Initialize optimizer - set settings,
    # learning rate of 1. is default for this optimizer
    def __init__(self, learning_rate=1., decay=0., momentum=0.):
        self.learning_rate = learning_rate
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
        self.momentum = momentum

    # Call once before any parameter updates
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * \
                (1. / (1. + self.decay * self.iterations))

    # Update parameters
    def update_params(self, layer):

        # If we use momentum
        if self.momentum:

            # If layer does not contain momentum arrays, create them
            # filled with zeros
            if not hasattr(layer, 'weight_momentums'):
                layer.weight_momentums = np.zeros_like(layer.weights)
                # If there is no momentum array for weights
                # The array doesn't exist for biases yet either.
                layer.bias_momentums = np.zeros_like(layer.biases)

            # Build weight updates with momentum - take previous
            # updates multiplied by retain factor and update with
            # current gradients
            weight_updates = \
                self.momentum * layer.weight_momentums - \
                self.current_learning_rate * layer.dweights
            layer.weight_momentums = weight_updates

            # Build bias updates
            bias_updates = \
                self.momentum * layer.bias_momentums - \
                self.current_learning_rate * layer.dbiases
            layer.bias_momentums = bias_updates

        # Vanilla SGD updates (as before momentum update)
        else:
            weight_updates = -self.current_learning_rate * \
                             layer.dweights
            bias_updates = -self.current_learning_rate * \
                           layer.dbiases

        # Update weights and biases using either
        # vanilla or momentum updates
        layer.weights += weight_updates
        layer.biases += bias_updates


    # Call once after any parameter updates
    def post_update_params(self):
        self.iterations += 1


In [35]:
dense1 = Layer_Dense(2, 64)
activation1 = Activation_ReLU()
dense2 = Layer_Dense( 64 , 3 )
activation2 = Activation_Softmax()

# Create optimizer
optimizer = Optimizer_SGD(learning_rate = 1, decay = 1e-3, momentum = 0.5)

# Train in loop
for epoch in range ( 10001 ):

    ##training
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    loss = categorical_crossentropy_loss(activation2.output, y)
    loss_grad = categorical_crossentropy_loss_gradient(activation2.output, y) #dvalues

    # loss = loss_activation.forward(dense2.output, y)

    predictions = np.argmax(activation2.output, axis = 1 )
    if len (y.shape) == 2 :
      y = np.argmax(y, axis = 1 )
    accuracy = np.mean(predictions == y)

    if not epoch % 100 :
      print(f"epoch:{epoch} ,acc:{accuracy:.3f} ,loss:{loss:.3f} ,lr:{optimizer.current_learning_rate}")


    # # Backward pass
    activation2.backward(loss_grad)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Print gradients
    # print (dense1.dweights)
    # print (dense1.dbiases)
    # print (dense2.dweights)
    # print (dense2.dbiases)

    # Update weights and biases
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch:0 ,acc:0.307 ,loss:1.098 ,lr:1
epoch:100 ,acc:0.410 ,loss:1.070 ,lr:0.9099181073703367
epoch:200 ,acc:0.430 ,loss:1.061 ,lr:0.8340283569641367
epoch:300 ,acc:0.450 ,loss:1.044 ,lr:0.7698229407236336
epoch:400 ,acc:0.463 ,loss:1.024 ,lr:0.7147962830593281
epoch:500 ,acc:0.553 ,loss:0.995 ,lr:0.66711140760507
epoch:600 ,acc:0.500 ,loss:0.991 ,lr:0.6253908692933083
epoch:700 ,acc:0.553 ,loss:0.960 ,lr:0.5885815185403178
epoch:800 ,acc:0.573 ,loss:0.919 ,lr:0.5558643690939411
epoch:900 ,acc:0.587 ,loss:0.882 ,lr:0.526592943654555
epoch:1000 ,acc:0.633 ,loss:0.847 ,lr:0.5002501250625312
epoch:1100 ,acc:0.603 ,loss:0.831 ,lr:0.4764173415912339
epoch:1200 ,acc:0.700 ,loss:0.791 ,lr:0.45475216007276037
epoch:1300 ,acc:0.687 ,loss:0.785 ,lr:0.43497172683775553
epoch:1400 ,acc:0.653 ,loss:0.750 ,lr:0.4168403501458941
epoch:1500 ,acc:0.633 ,loss:0.742 ,lr:0.4001600640256102
epoch:1600 ,acc:0.710 ,loss:0.719 ,lr:0.3847633705271258
epoch:1700 ,acc:0.660 ,loss:0.705 ,lr:0.3705075954057058
epoc

Output for Momentum and Vanilla Optiimizer

Now implementing Adam Optimizer

In [38]:
#Adam Optimizer
# Adam optimizer
class Optimizer_Adam:

    # Initialize optimizer - set settings
    def __init__(self, learning_rate=0.001, decay=0., epsilon=1e-7,
                 beta_1=0.9, beta_2=0.999):
        self.learning_rate = learning_rate
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
        self.epsilon = epsilon
        self.beta_1 = beta_1
        self.beta_2 = beta_2

    # Call once before any parameter updates
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * (1. / (1. + self.decay * self.iterations))

    # Update parameters
    def update_params(self, layer):

        # If layer does not contain cache arrays,
        # create them filled with zeros
        if not hasattr(layer, 'weight_cache'):
            layer.weight_momentums = np.zeros_like(layer.weights)
            layer.weight_cache = np.zeros_like(layer.weights)
            layer.bias_momentums = np.zeros_like(layer.biases)
            layer.bias_cache = np.zeros_like(layer.biases)

        # Update momentum  with current gradients
        layer.weight_momentums = self.beta_1 * layer.weight_momentums + (1 - self.beta_1) * layer.dweights
        layer.bias_momentums = self.beta_1 * layer.bias_momentums + (1 - self.beta_1) * layer.dbiases

        # Get corrected momentum
        # self.iteration is 0 at first pass
        # and we need to start with 1 here
        weight_momentums_corrected = layer.weight_momentums / (1 - self.beta_1 ** (self.iterations + 1))
        bias_momentums_corrected = layer.bias_momentums / (1 - self.beta_1 ** (self.iterations + 1))
        # Update cache with squared current gradients
        layer.weight_cache = self.beta_2 * layer.weight_cache + (1 - self.beta_2) * layer.dweights**2

        layer.bias_cache = self.beta_2 * layer.bias_cache + (1 - self.beta_2) * layer.dbiases**2
        # Get corrected cache
        weight_cache_corrected = layer.weight_cache / (1 - self.beta_2 ** (self.iterations + 1))
        bias_cache_corrected = layer.bias_cache / (1 - self.beta_2 ** (self.iterations + 1))

        # Vanilla SGD parameter update + normalization
        # with square rooted cache
        layer.weights += -self.current_learning_rate * weight_momentums_corrected / (np.sqrt(weight_cache_corrected) + self.epsilon)
        layer.biases += -self.current_learning_rate * bias_momentums_corrected / (np.sqrt(bias_cache_corrected) + self.epsilon)

    # Call once after any parameter updates
    def post_update_params(self):
        self.iterations += 1


In [39]:
dense1 = Layer_Dense(2, 64)
activation1 = Activation_ReLU()
dense2 = Layer_Dense( 64 , 3 )
activation2 = Activation_Softmax()

# Create optimizer
optimizer = Optimizer_Adam(learning_rate = 0.02, decay = 1e-5)

# Train in loop
for epoch in range ( 10001 ):

    ##training
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    loss = categorical_crossentropy_loss(activation2.output, y)
    loss_grad = categorical_crossentropy_loss_gradient(activation2.output, y) #dvalues

    predictions = np.argmax(activation2.output, axis = 1 )
    if len (y.shape) == 2 :
      y = np.argmax(y, axis = 1 )
    accuracy = np.mean(predictions == y)

    if not epoch % 100 :
      print(f"epoch:{epoch} ,acc:{accuracy:.3f} ,loss:{loss:.3f} ,lr:{optimizer.current_learning_rate}")


    # # Backward pass
    activation2.backward(loss_grad)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Print gradients
    # print (dense1.dweights)
    # print (dense1.dbiases)
    # print (dense2.dweights)
    # print (dense2.dbiases)

    # Update weights and biases
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch:0 ,acc:0.390 ,loss:1.098 ,lr:0.02
epoch:100 ,acc:0.727 ,loss:0.715 ,lr:0.01998021958261321
epoch:200 ,acc:0.833 ,loss:0.502 ,lr:0.019960279044701046
epoch:300 ,acc:0.853 ,loss:0.386 ,lr:0.019940378268975763
epoch:400 ,acc:0.900 ,loss:0.299 ,lr:0.01992051713662487
epoch:500 ,acc:0.913 ,loss:0.256 ,lr:0.01990069552930875
epoch:600 ,acc:0.917 ,loss:0.231 ,lr:0.019880913329158343
epoch:700 ,acc:0.917 ,loss:0.210 ,lr:0.019861170418772778
epoch:800 ,acc:0.923 ,loss:0.197 ,lr:0.019841466681217078
epoch:900 ,acc:0.923 ,loss:0.187 ,lr:0.01982180200001982
epoch:1000 ,acc:0.927 ,loss:0.179 ,lr:0.019802176259170884
epoch:1100 ,acc:0.923 ,loss:0.172 ,lr:0.01978258934311912
epoch:1200 ,acc:0.923 ,loss:0.165 ,lr:0.01976304113677013
epoch:1300 ,acc:0.933 ,loss:0.157 ,lr:0.019743531525483964
epoch:1400 ,acc:0.933 ,loss:0.152 ,lr:0.01972406039507293
epoch:1500 ,acc:0.943 ,loss:0.145 ,lr:0.019704627631799327
epoch:1600 ,acc:0.947 ,loss:0.137 ,lr:0.019685233122373254
epoch:1700 ,acc:0.950 ,loss:0.13

Output with Adam Optimizer

Problem of overfitting may arrive, So adding regularization terms to dense layers to avoid overfitting

In [46]:
# Dense layer
class Layer_Dense:

    # Layer initialization
    def __init__(self, n_inputs, n_neurons,
                 weight_regularizer_l1=0, weight_regularizer_l2=0,
                 bias_regularizer_l1=0, bias_regularizer_l2=0):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        # Set regularization strength
        self.weight_regularizer_l1 = weight_regularizer_l1
        self.weight_regularizer_l2 = weight_regularizer_l2
        self.bias_regularizer_l1 = bias_regularizer_l1
        self.bias_regularizer_l2 = bias_regularizer_l2

    # Forward pass
    def forward(self, inputs):
        # Remember input values
        self.inputs = inputs
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases
    # Backward pass
    def backward(self, dvalues):
        # Gradients on parameters
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)

        # Gradients on regularization
        # L1 on weights
        if self.weight_regularizer_l1 > 0:
            dL1 = np.ones_like(self.weights)
            dL1[self.weights < 0] = -1
            self.dweights += self.weight_regularizer_l1 * dL1
        # L2 on weights
        if self.weight_regularizer_l2 > 0:
            self.dweights += 2 * self.weight_regularizer_l2 * \
                             self.weights
        # L1 on biases
        if self.bias_regularizer_l1 > 0:
            dL1 = np.ones_like(self.biases)
            dL1[self.biases < 0] = -1
            self.dbiases += self.bias_regularizer_l1 * dL1
        # L2 on biases
        if self.bias_regularizer_l2 > 0:
            self.dbiases += 2 * self.bias_regularizer_l2 * \
                            self.biases

        # Gradient on values
        self.dinputs = np.dot(dvalues, self.weights.T)


Regularization loss calculate function

In [47]:
# Regularization loss calculation
def regularization_loss(layer):
    # 0 by default
    regularization_loss = 0
    # L1 regularization - weights
    # calculate only when factor greater than 0
    if layer.weight_regularizer_l1 > 0 :
      regularization_loss += layer.weight_regularizer_l1 * \
      np.sum(np.abs(layer.weights))
    # L2 regularization - weights
    if layer.weight_regularizer_l2 > 0 :
      regularization_loss += layer.weight_regularizer_l2 * \
      np.sum(layer.weights * \
      layer.weights)

    # L1 regularization - biases
    # calculate only when factor greater than 0
    if layer.bias_regularizer_l1 > 0 :
      regularization_loss += layer.bias_regularizer_l1 * \
      np.sum(np.abs(layer.biases))
    # L2 regularization - biases
    if layer.bias_regularizer_l2 > 0 :
      regularization_loss += layer.bias_regularizer_l2 * \
      np.sum(layer.biases * \
      layer.biases)
    return regularization_loss

Testing with regularization

In [48]:
X, y = spiral_data( samples = 100 , classes = 3 )

dense1 = Layer_Dense(2, 64, weight_regularizer_l2 = 5e-4, bias_regularizer_l2 = 5e-4)
activation1 = Activation_ReLU()
dense2 = Layer_Dense( 64 , 3 )
activation2 = Activation_Softmax()
# loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

# Create optimizer
optimizer = Optimizer_Adam(learning_rate = 0.02 , decay = 5e-7)

# Train in loop
for epoch in range ( 10001 ):

    ##training
    dense1.forward(X)
    activation1.forward(dense1.output)
    dense2.forward(activation1.output)
    activation2.forward(dense2.output)

    data_loss = categorical_crossentropy_loss(activation2.output, y)
    loss_grad = categorical_crossentropy_loss_gradient(activation2.output, y) #dvalues

    regular_loss = regularization_loss(dense1) + regularization_loss(dense2)
    # loss = loss_activation.forward(dense2.output, y)
    loss = data_loss + regular_loss
    predictions = np.argmax(activation2.output, axis = 1 )
    if len (y.shape) == 2 :
      y = np.argmax(y, axis = 1 )
    accuracy = np.mean(predictions == y)

    if not epoch % 100 :
      print(f"epoch:{epoch} ,acc:{accuracy:.3f} ,loss:{loss:.3f} , regular_loss: {regular_loss}, lr:{optimizer.current_learning_rate}")


    # # Backward pass
    activation2.backward(loss_grad)
    dense2.backward(activation2.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    # Print gradients
    # print (dense1.dweights)
    # print (dense1.dbiases)
    # print (dense2.dweights)
    # print (dense2.dbiases)

    # Update weights and biases
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch:0 ,acc:0.277 ,loss:1.099 , regular_loss: 6.427696789317836e-06, lr:0.02
epoch:100 ,acc:0.587 ,loss:0.921 , regular_loss: 0.02475313947586476, lr:0.019999010049002574
epoch:200 ,acc:0.720 ,loss:0.756 , regular_loss: 0.05934568290388974, lr:0.019998010197985302
epoch:300 ,acc:0.790 ,loss:0.667 , regular_loss: 0.08226228737560022, lr:0.019997010446938183
epoch:400 ,acc:0.823 ,loss:0.624 , regular_loss: 0.09371363482855283, lr:0.01999601079584623
epoch:500 ,acc:0.840 ,loss:0.584 , regular_loss: 0.0999552241905841, lr:0.01999501124469445
epoch:600 ,acc:0.850 ,loss:0.557 , regular_loss: 0.103155734476285, lr:0.01999401179346786
epoch:700 ,acc:0.857 ,loss:0.536 , regular_loss: 0.1046686584102526, lr:0.01999301244215147
epoch:800 ,acc:0.870 ,loss:0.519 , regular_loss: 0.10527175925671167, lr:0.0199920131907303
epoch:900 ,acc:0.863 ,loss:0.504 , regular_loss: 0.10542987234675266, lr:0.019991014039189386
epoch:1000 ,acc:0.870 ,loss:0.491 , regular_loss: 0.10504053664500443, lr:0.0199900149

Finally tested all our different layers